{
 "title": "Carbon-Statistics",
 "time": { "from": "now-15m", "to": "now" },
 "panels": [
  {
   "title": "Total saved Carton-Intensity %",
   "type": "gauge",
   "description": "Saved carbon intensity over all jobs and all time",
   "gridPos": { "h": 8, "w": 7, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "%" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expression": "100-($A/$B)*100", "type": "math" }
   ]
  },
  {
   "title": "Average Planed Carbon Intensity (gCO2/kWh)",
   "type": "gauge",
   "description": "Carbon intensity before the job was time-shifted (planed execution time by cron trigger)",
   "gridPos": { "h": 8, "w": 17, "x": 7, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "SELECT AVG(actual_carbon_intensity) AS \"avg_actual_carbon_intensity\", job_name FROM carbon_statistics GROUP BY job_name LIMIT 50 "
    }
   ]
  },
  {
   "title": "Total saved Carton-Intensity (gCO2/kWh)",
   "type": "gauge",
   "description": "Saved carbon intensity over all jobs and all time",
   "gridPos": { "h": 8, "w": 7, "x": 0, "y": 8 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expression": "$B-$A", "type": "math" }
   ]
  },
  {
   "title": "Average Used Carbon Intensity (gCO2/kWh)",
   "type": "gauge",
   "description": "Carbon intensity after the job was time-shifted",
   "gridPos": { "h": 8, "w": 17, "x": 7, "y": 8 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "SELECT AVG(optimal_carbon_intensity) AS \"avg_optimal_carbon_intensity\", job_name FROM carbon_statistics GROUP BY job_name LIMIT 50 "
    }
   ]
  },
  {
   "title": "Total executed Jobs",
   "type": "table",
   "gridPos": { "h": 7, "w": 7, "x": 0, "y": 16 },
   "targets": [
    {
     "rawSql": "SELECT job_name AS \"Job\", COUNT(job_execution_id) AS \"count\" FROM carbon_statistics GROUP BY job_name LIMIT 50 "
    }
   ]
  },
  {
   "title": "Jobs waiting for execution",
   "type": "table",
   "description": "Jobs waiting for execution after they are rescheduled by the carbon-aware trigger",
   "gridPos": { "h": 7, "w": 17, "x": 7, "y": 16 },
   "targets": [
    {
     "rawSql": "SELECT job_name AS \"Job-Name\", next_fire_time AS \"time\" FROM qrtz_triggers WHERE trigger_state = 'WAITING' GROUP BY next_fire_time, job_name LIMIT 50 "
    }
   ]
  }
 ]
}